requires 'perl' => '5.008001';
requires 'locale';
requires 'sort';
requires 'Carp';
requires 'Exporter' => '5.57';
requires 'File::Glob';
requires 'File::Spec';
requires 'Sort::filevercmp';
test_requires 'Cwd';
test_requires 'File::pushd';
test_requires 'File::Temp';
test_requires 'Test::More' => '0.88';
